### ISSUE TITLE
pkg-config: Add Fortran support.

### ISSUE THREAD

**Issue by samuelkgutierrez** [hpc/quo-vadis#20]
Add Fortran support to our `pkg-config`.

Adding @andreapiacentini to also track this issue.

**Comment by samuelkgutierrez** [comment]
@andreapiacentini please let me know if what I added in 64d3ac65fb4b50d974548fc5ef67fe997c97c69a is sufficient. I don't know much about `pkg-config`, so perhaps there is a nicer way. I'm open to suggestions.

**Comment by andreapiacentini** [comment]
The machinery is now working on my PC with Intel or GNU compilers.
In my "suggestion" branch I added the lines corresponding to the fortran pkg-config in the src/fortran/CMakeLists.txt so that they are conditionally generated.
I'm probably the only one using pkg-config instead of cmake and I use MPI. But Edgar recalled that QV has to work also without MPI. That's why I tried to generate pkg-config files also without MPI_FOUND.
In order to avoid multiplying the pc.in in the sources, I just kept one using the @QV_PKG_LIBRARIES@ cmake variable and always starting from the same pc.in in the configure sections with 4 different output names, then used in the install (cf lines 224 and following in the src/CMakeLists.txt of the fix/cmake_install branch.

**Comment by andreapiacentini** [comment]
Following what said before, the tests/CMakeLists won't work without MPI_FOUND.
Compare the current one with the last commit in fix/cmake_install for the needed fixes.
Moreover, I've added a switch for disabiling MPI, useful for checks and tests, I guess, in the main CMakeLists.txt

**Comment by samuelkgutierrez** [comment]
Looks like this is now resolved.
