### ISSUE TITLE
qv_thread: Interface Consideration

### ISSUE THREAD

**Issue by samuelkgutierrez** [hpc/quo-vadis#64]
Would it make sense to add two members to `qv_thread_args_t`:
* A function pointer that matches `pthread_create()`'s `start_routine` signature
* A user data payload pointer (`void *`)?

This two-tier approach seems reasonable to me for a variety of reasons; here are two:
* Provides a way to separate layout policy from workload
* Potentially simplifies in porting because an already-established callback and associated data can be left unchanged.

**Comment by GuillaumeMercier** [comment]
> Would it make sense to add two members to `qv_thread_args_t`:
> 
>     * A function pointer that matches `pthread_create()`'s `start_routine` signature
> 
>     * A user data payload pointer (`void *`)?

Yes, I was thinking about it too. I think that there was an issue with this approach but I fail to remember it.
I will think about it again.

**Comment by GuillaumeMercier** [comment]
> > Would it make sense to add two members to `qv_thread_args_t`:
> > ```
> > * A function pointer that matches `pthread_create()`'s `start_routine` signature
> > 
> > * A user data payload pointer (`void *`)?
> > ```
> 
> Yes, I was thinking about it too. I think that there was an issue with this approach but I fail to remember it. I will think about it again.

That's a lot of thinking here.

**Comment by GuillaumeMercier** [comment]
I'm not sure I completely get what you want to do here.

The `qv_thread_args_t` type was introduced to ease the passing of arguments to the function that is 
supposed to be called by `pthread_create`, function that has to make a call to `qv_thread_layout_apply`.

As the consequence of this choice is that  the code for OpenMP version of the example get more 
complicated. Therefore, maybe having to variants of the same function could be appropriate
(remember that currently, there is no way to determine that OpenMP is not used in a Pthreads-only
version of a program when OpenMP support  is enabled at configure time, therefore two functions and 
no `#ifdef` possible unless  some magic is involved).

Now, back to the function and arg pointers again. I see the benefit to pass such information so that 
the function executed by the thread would look like:
```
void *start_routine(void *arg)
{
   qv_thread_layout_create( arg->arg1, arg->arg2, etc);
  
   arg->workoad_func(arg->payload_arg);

   pthread_exit();
}
```
So, to me, the workload function pointer and the payload arg pointer should be part of the 
data structure that is supposed to regroup the arguments passed to `qv_thread_layout_apply`,
but to a data struct that should ne passed to the start_routine executed by the nexly created thread.
That's bascially the `args_t`in the example.  But  should we have a determined type for this or
let the user/app developer do as they wish? I think that is the main reason why I did not go 
down this route but to be honest, I don't think that it's a strong argument and I find the pointers
idea compelling.

What do you think?

**Comment by samuelkgutierrez** [comment]
@GuillaumeMercier and I spoke offline. His approach makes sense to me now.
